/camera/back_middle:
  camera_model: pinhole
  device_name: /dev/video6
  imu_to_camera_rotation_offset_xyz:
  - 0.0
  - 0.0
  - 0.0
  imu_to_camera_translation_xyz:
  - 0
  - 0.0
  - 0
  input_mode: ros_topic
  resolution:
  - 3840
  - 2160
  ros_topic: /camera/back_middle/compressed
/camera/front_left:
  camera_model: pinhole
  device_name: /dev/video6
  imu_to_camera_rotation_offset_xyz:
  - 0.0
  - 0.0
  - 0.0
  imu_to_camera_translation_xyz:
  - 0
  - 0.0
  - 0
  input_mode: ros_topic
  resolution:
  - 3840
  - 2160
  ros_topic: /camera/front_left/compressed
/camera/front_middle:
  camera_model: pinhole
  device_name: /dev/video6
  imu_to_camera_rotation_offset_xyz:
  - 0.0
  - 0.0
  - 0.0
  imu_to_camera_translation_xyz:
  - 0
  - 0.0
  - 0
  input_mode: ros_topic
  resolution:
  - 3840
  - 2160
  ros_topic: /camera/front_middle/compressed
/camera/front_right:
  camera_model: pinhole
  device_name: /dev/video6
  imu_to_camera_rotation_offset_xyz:
  - 0.0
  - 0.0
  - 0.0
  imu_to_camera_translation_xyz:
  - 0
  - 0.0
  - 0
  input_mode: ros_topic
  resolution:
  - 3840
  - 2160
  ros_topic: /camera/front_right/compressed
/camera/left_back:
  camera_model: pinhole
  device_name: /dev/video6
  imu_to_camera_rotation_offset_xyz:
  - 0.0
  - 0.0
  - 0.0
  imu_to_camera_translation_xyz:
  - 0
  - 0.0
  - 0
  input_mode: ros_topic
  resolution:
  - 3840
  - 2160
  ros_topic: /camera/left_back/compressed
/camera/left_front:
  camera_model: pinhole
  device_name: /dev/video6
  imu_to_camera_rotation_offset_xyz:
  - 0.0
  - 0.0
  - 0.0
  imu_to_camera_translation_xyz:
  - 0
  - 0.0
  - 0
  input_mode: ros_topic
  resolution:
  - 3840
  - 2160
  ros_topic: /camera/left_front/compressed
/camera/lidar_left:
  camera_model: pinhole
  device_name: /dev/video0
  imu_to_camera_rotation_offset_xyz:
  - 0.0
  - 0.0
  - 0.0
  imu_to_camera_translation_xyz:
  - 0
  - 0.0
  - 0
  input_mode: ros_topic
  resolution:
  - 3840
  - 2160
  ros_topic: /camera/lidar_left/compressed
/camera/lidar_right:
  camera_model: pinhole
  device_name: /dev/video1
  distortion_coefficients:
  - -0.7645478821204835
  - 0.819536643206817
  - -0.00403678003200401
  - 0.011373937879165755
  - -0.44871487064576354
  imu_to_camera_rotation_offset_xyz:
  - 0.0
  - 0.0
  - 0.0
  imu_to_camera_translation_xyz:
  - 0
  - 0.0
  - 0
  input_mode: ros_topic
  intrinsics_matrix:
  - 3019.000394024139
  - 0.0
  - 1894.2403596034676
  - 0.0
  - 3011.4135764105254
  - 1165.244488990604
  - 0.0
  - 0.0
  - 1.0
  resolution:
  - 3840
  - 2160
  ros_topic: /camera/lidar_right/compressed
/camera/right_back:
  camera_model: pinhole
  device_name: /dev/video6
  imu_to_camera_rotation_offset_xyz:
  - 0.0
  - 0.0
  - 0.0
  imu_to_camera_translation_xyz:
  - 0
  - 0.0
  - 0
  input_mode: ros_topic
  resolution:
  - 3840
  - 2160
  ros_topic: /camera/right_back/compressed
/camera/right_front:
  camera_model: pinhole
  device_name: /dev/video6
  distortion_coefficients:
  - -0.38470622135537347
  - 0.17225034701757974
  - 0.0018429244897022914
  - 0.0017820508174547487
  - -0.035397811118394296
  imu_to_camera_rotation_offset_xyz:
  - 0.0
  - 0.0
  - 0.0
  imu_to_camera_translation_xyz:
  - 0
  - 0.0
  - 0
  input_mode: ros_topic
  intrinsics_matrix:
  - 2101.4851244690412
  - 0.0
  - 1832.5738587242886
  - 0.0
  - 2083.737418489394
  - 1006.6772473279825
  - 0.0
  - 0.0
  - 1.0
  resolution:
  - 3840
  - 2160
  ros_topic: /camera/right_front/compressed
