/camera/jianghuai:
  camera_model: pinhole
  device_name: /dev/video0
  distortion_coefficients:
  - -0.8276
  - 2.2485
  - 0
  - 0
  - 0
  input_mode: ros_topic
  intrinsics_matrix:
  - 4324
  - 0.0
  - 1313
  - 0.0
  - 4432.7
  - 437.755
  - 0.0
  - 0.0
  - 1.0
  resolution:
  - 1920
  - 1080
  ros_topic: /cam_pub_0_node/camera/image_video4/compressed