/camera/rostopic_test:
  camera_model: pinhole
  device_name: /dev/fisheye_left
  input_mode: ros_topic
  resolution:
  - 2048
  - 1024
  ros_topic: /usb_cam/image_raw/compressed
/camera/fisheye_test:
  camera_model: fisheye
  device_name: /dev/fisheye_left
  distortion_coefficients:
  - -1.3149594724938338
  - 20.976130474047952
  - -148.4752794077928
  - 354.3873777577522
  input_mode: device_name
  intrinsics_matrix:
  - 1967.2949679224578
  - 0.0
  - 1028.8543533405289
  - 0.0
  - 1958.8101491897553
  - 674.9530720361591
  - 0.0
  - 0.0
  - 1.0
  resolution:
  - 1920
  - 1080
  ros_topic: /usb_cam/image_raw/compressed
  scale_xy:
  - 1.0
  - 1.0
  shift_xy:
  - 0
  - 0
/camera/pinhole_test:
  camera_model: pinhole
  device_name: /dev/fisheye_left
  distortion_coefficients:
  - -0.7062816619873047
  - -0.6785455346107483
  - 0.1770123541355133
  - -0.031898993998765945
  - 1.08749258518219
  input_mode: device_name
  intrinsics_matrix:
  - 2410.587158203125
  - 0.0
  - 1101.84765625
  - 0.0
  - 2237.48779296875
  - 48.55520248413086
  - 0.0
  - 0.0
  - 1.0
  resolution:
  - 1920
  - 1080
  ros_topic: /usb_cam/image_raw/compressed
  imu_to_camera_translation:
  - 1.5
  - 0
  - 1.5
  imu_to_camera_rotation_offset:
  - 0
  - 0
  - 0
/camera/back_wild:
  camera_model: fisheye
  device_name: /dev/fisheye_left
  input_mode: ros_topic
  resolution:
  - 1920
  - 1080
  ros_topic: /camera/back_wild/compressed
  scale_xy:
  - 1.0
  - 1.0
  shift_xy:
  - 0
  - 0
/camera/front_wild:
  camera_model: fisheye
  device_name: /dev/fisheye_left
  input_mode: ros_topic
  resolution:
  - 1920
  - 1080
  ros_topic: /camera/front_wild/compressed
  scale_xy:
  - 1.0
  - 1.0
  shift_xy:
  - 0
  - 0
/camera/left_wild:
  camera_model: fisheye
  device_name: /dev/fisheye_left
  input_mode: ros_topic
  resolution:
  - 1920
  - 1080
  ros_topic: /camera/left_wild/compressed
  scale_xy:
  - 1.0
  - 1.0
  shift_xy:
  - 0
  - 0
/camera/right_wild:
  camera_model: fisheye
  device_name: /dev/fisheye_left
  input_mode: ros_topic
  resolution:
  - 1920
  - 1080
  ros_topic: /camera/right_wild/compressed
  scale_xy:
  - 1.0
  - 1.0
  shift_xy:
  - 0
  - 0