# /camera/mono_pinhole_camera_test:
#   camera_model: pinhole
#   device_name: /dev/videox
#   input_mode: device_name
#   resolution:
#   - 1920
#   - 1080
#   ros_topic: /usb_cam/image_raw/compressed
/camera/imu_to_camera_test:
  camera_model: pinhole
  device_name: /dev/videox
  distortion_coefficients:
  - -0.6068
  - 1.6439
  - 0.0336
  - -0.0038
  - -9.4576
  imu_to_camera_rotation_offset_xyz:
  - 0.0
  - 0.0
  - 0.0
  imu_to_camera_translation_xyz:
  - 0.0
  - 0
  - 0
  input_mode: ros_topic
  intrinsics_matrix:
  - 4756
  - 0.0
  - -121 
  - 0.0
  - 4767.2 
  - 1261 
  - 0.0
  - 0.0
  - 1.0
  resolution:
  - 1920
  - 1080
  ros_topic: /cam_pub_0_node/camera/image_video4/compressed
